on:
  schedule:
    - cron:  '37 * * * *'
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      # - name: Build
      #   run: npm install && npm run build
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Specify the version of Python you need

    # Installs dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    # Runs a Python script
      - name: Run script
        run: PYTHONPATH="$PYTHONPATH:$PWD" python src/main.py

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: willaidothat # e.g. 'my-project'
          directory: static # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
